# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zeddb}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zedkit"]
  s.date = %q{2011-01-18}
  s.description = %q{gem for dynamic ZedDB models generated automatically from the ZedAPI at initialization}
  s.email = %q{support@zedkit.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/zed_record.rb",
    "lib/zed_record/initializer.rb",
    "test/helper.rb",
    "test/test_models.rb"
  ]
  s.homepage = %q{http://github.com/zedkit/zed_record}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{zed_record}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem for dynamic ZedDB models}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<zedkit>, [">= 0"])
      s.add_runtime_dependency(%q<zeddb>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.4"])
    else
      s.add_dependency(%q<zedkit>, [">= 0"])
      s.add_dependency(%q<zeddb>, [">= 0"])
      s.add_dependency(%q<json>, [">= 1.4.4"])
    end
  else
    s.add_dependency(%q<zedkit>, [">= 0"])
    s.add_dependency(%q<zeddb>, [">= 0"])
    s.add_dependency(%q<json>, [">= 1.4.4"])
  end
end

